[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-cache"

  [plugins.inputs]
    paths = [
      "node_modules/.cache",
      ".netlify/cache",
      "public/build", # ou dist, selon ton dossier
    ]
