[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_VERSION = "20.11.1"
  PHP_VERSION = "8.3"
  PYTHON_VERSION = "3.10"
  RUBY_VERSION = "3.2.2"
  GO_VERSION = "1.21"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
